spring:
  application:
    name: ms-vet-users
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/vetapp
    username: postgres
    password: zerocode

server:
  port: 8081

logging:
  level:
    org.hibernate.SQL: DEBUG